// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_TOOLBAR_H
#define _UI_COMP_TOOLBAR_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Toolbar
#define UI_COMP_TOOLBAR_TOOLBAR 0
#define _UI_COMP_TOOLBAR_NUM 1
lv_obj_t * ui_Toolbar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
