// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT Toolbar

lv_obj_t * ui_Toolbar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Toolbar;
    cui_Toolbar = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Toolbar);
    lv_obj_set_width(cui_Toolbar, 100);
    lv_obj_set_height(cui_Toolbar, 50);
    lv_obj_set_x(cui_Toolbar, 16);
    lv_obj_set_y(cui_Toolbar, -74);
    lv_obj_set_align(cui_Toolbar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Toolbar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Toolbar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_Toolbar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TOOLBAR_NUM);
    children[UI_COMP_TOOLBAR_TOOLBAR] = cui_Toolbar;
    lv_obj_add_event_cb(cui_Toolbar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Toolbar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Toolbar_create_hook(cui_Toolbar);
    return cui_Toolbar;
}

