// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_timestring = NULL;
lv_obj_t * ui_datestring = NULL;
lv_obj_t * ui_bpm = NULL;
lv_obj_t * ui_spo2 = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_battpercent = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timestring = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timestring, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timestring, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timestring, 1);
    lv_obj_set_y(ui_timestring, -46);
    lv_obj_set_align(ui_timestring, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timestring, "12:30");
    lv_obj_set_style_text_color(ui_timestring, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timestring, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_timestring, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timestring, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datestring = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_datestring, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_datestring, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_datestring, 0);
    lv_obj_set_y(ui_datestring, -11);
    lv_obj_set_align(ui_datestring, LV_ALIGN_CENTER);
    lv_label_set_text(ui_datestring, "Tue, 11 Nov");
    lv_obj_set_style_text_color(ui_datestring, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_datestring, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_datestring, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bpm = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_bpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bpm, -58);
    lv_obj_set_y(ui_bpm, 64);
    lv_obj_set_align(ui_bpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bpm, "80\nbpm");
    lv_obj_set_style_text_color(ui_bpm, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_bpm, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spo2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_spo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spo2, 2);
    lv_obj_set_y(ui_spo2, 64);
    lv_obj_set_align(ui_spo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spo2, "80\nbpm");
    lv_obj_set_style_text_color(ui_spo2, lv_color_hex(0x00FF17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_spo2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, 61);
    lv_obj_set_y(ui_temp, 64);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "80\nbpm");
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFF5500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_temp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 23);
    lv_obj_set_height(ui_Bar1, 13);
    lv_obj_set_x(ui_Bar1, 2);
    lv_obj_set_y(ui_Bar1, -82);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x343434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFF800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_battpercent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_battpercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battpercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battpercent, 3);
    lv_obj_set_y(ui_battpercent, -97);
    lv_obj_set_align(ui_battpercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battpercent, "10%");
    lv_obj_set_style_text_color(ui_battpercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_battpercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_714429375);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Image4, 3);
    lv_obj_set_y(ui_Image4, 30);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 768);

    ui_Image5 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image5, &ui_img_1521379185);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Image5, -57);
    lv_obj_set_y(ui_Image5, 29);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 768);

    ui_Image6 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image6, &ui_img_1877372811);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Image6, 62);
    lv_obj_set_y(ui_Image6, 29);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 768);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_timestring = NULL;
    ui_datestring = NULL;
    ui_bpm = NULL;
    ui_spo2 = NULL;
    ui_temp = NULL;
    ui_Bar1 = NULL;
    ui_battpercent = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;

}
